schema:
  name: reporting
tables:
  monitor:
    - name: syncLog
      columns: "
        id BIGINT AUTO_INCREMENT NOT NULL,
        tableName VARCHAR(150) NOT NULL,
        date DATE NOT NULL,
        records INT NOT NULL,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
        "
      indexes:
        - name: IX_TableDate
          columns:
            - tableName
            - date
  fact:
    - name: wmsDocumentLines
      columns: "
        id CHAR(36) NOT NULL,
        documentType VARCHAR(50) NOT NULL,
        documentNo VARCHAR(50) NOT NULL,
        lineNo INT NOT NULL,
        sellToCustomerNo VARCHAR(50) NOT NULL,
        sellToCustomerNo2 VARCHAR(50),
        sellToCustomerName VARCHAR(150),
        buyFromVendorNo VARCHAR(50),
        buyFromVendorName VARCHAR(150),
        dossierNo VARCHAR(50),
        carrierTypeCode VARCHAR(50),
        currencyCode VARCHAR(10),
        currencyFactor DECIMAL(18,4),
        lineAmountLCY DECIMAL(18,4),
        type VARCHAR(50),
        no VARCHAR(50),
        externalNo VARCHAR(50),
        itemNo VARCHAR(50),
        description VARCHAR(255),
        description2 VARCHAR(255),
        baseUnitOfMeasureCode VARCHAR(20),
        unitOfMeasureCode VARCHAR(20),
        qtyPerUnitOfMeasure DECIMAL(18,4),
        quantity DECIMAL(18,4),
        quantityBase DECIMAL(18,4),
        qtyCreated DECIMAL(18,4),
        qtyOutstanding DECIMAL(18,4),
        qtyPosted DECIMAL(18,4),
        qtyBaseCreated DECIMAL(18,4),
        qtyBasePosted DECIMAL(18,4),
        qtyBaseOutstanding DECIMAL(18,4),
        storageChargeNo VARCHAR(50),
        unitPrice DECIMAL(18,4),
        lineAmount DECIMAL(18,4),
        carrierQuantity DECIMAL(18,4),
        carrierQtyCreated DECIMAL(18,4),
        carrierQtyPosted DECIMAL(18,4),
        qtyPerCarrier DECIMAL(18,4),
        defaultNetWeightPerUOM DECIMAL(18,4),
        carrierQtyOutstanding DECIMAL(18,4),
        createdDateTime DATETIME,
        createdUserID VARCHAR(50),
        modifiedDateTime DATETIME,
        modifiedUserID VARCHAR(50),
        orderUnitOfMeasureCode VARCHAR(20),
        qtyPerOrderUnitOfMeasure DECIMAL(18,4),
        tareWeightPerUoM DECIMAL(18,4),
        grossWeightPerUoM DECIMAL(18,4),
        netWeightPerUoM DECIMAL(18,4),
        volumeWeight DECIMAL(18,4),
        tareWeight DECIMAL(18,4),
        grossWeight DECIMAL(18,4),
        netWeight DECIMAL(18,4),
        grossWeightCreated DECIMAL(18,4),
        netWeightCreated DECIMAL(18,4),
        batchNo VARCHAR(50),
        externalBatchNo VARCHAR(50),
        grossWeightPosted DECIMAL(18,4),
        netWeightPosted DECIMAL(18,4),
        grossWeightOutstanding DECIMAL(18,4),
        netWeightOutstanding DECIMAL(18,4),
        qtyToHandle DECIMAL(18,4),
        customerItemNo2 VARCHAR(50),
        batchNo2 VARCHAR(50),
        storageChargeNo2 VARCHAR(50),
        unitOfMeasureCode2 VARCHAR(20),
        locationNo VARCHAR(50),
        buildingCode VARCHAR(50),
        customsCode VARCHAR(50),
        tariffNo VARCHAR(50),
        countryOfOriginCode VARCHAR(10),
        countryPurchasedCode VARCHAR(10),
        customsValue DECIMAL(18,4),
        customsValuePer DECIMAL(18,4),
        nctsDocumentNo VARCHAR(50),
        additionalDocumentNo VARCHAR(50),
        placeOfCertificateDelivery VARCHAR(150),
        destination VARCHAR(150),
        tariffDescription VARCHAR(255),
        declarationDocumentType VARCHAR(50),
        customsCurrencyCode VARCHAR(10),
        containerNo VARCHAR(50),
        vesselNo VARCHAR(50),
        itemHandling VARCHAR(50),
        orderTypeCode VARCHAR(50),
        entrepotStorage VARCHAR(50),
        commentText VARCHAR(255),
        externalDocumentNo VARCHAR(50),
        shortcutDimension1Code VARCHAR(50),
        shortcutDimension2Code VARCHAR(50),
        postingDate DATE,
        invoiceType VARCHAR(50),
        invoiceNo VARCHAR(50),
        invoiceDate DATE,
        purchInvoiceNo VARCHAR(50),
        purchInvoiceDate DATE,
        reservationPosted TINYINT(1),
        agreementType VARCHAR(50),
        agreementNo VARCHAR(50),
        agreementLineNo INT,
        agreementDetailLineNo INT,
        agreementDetailLineType VARCHAR(50),
        senderAddressNo VARCHAR(50),
        isActivity TINYINT(1),
        shipToAddressNo VARCHAR(50),
        activityDate DATE,
        activityTime TIME,
        shipToAddressName VARCHAR(150),
        customsIssueDate DATE,
        declarationDocumentNo VARCHAR(50),
        attribute01 VARCHAR(100),
        attribute02 VARCHAR(100),
        attribute03 VARCHAR(100),
        attribute04 VARCHAR(100),
        attribute05 VARCHAR(100),
        attribute06 VARCHAR(100),
        isUTB BIT NULL,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: generalLedgerEntries
      columns: "
        id CHAR(36) NOT NULL,
        entryNo INT NOT NULL,
        gLAccountNo VARCHAR(50) NOT NULL,
        postingDate DATE NOT NULL,
        documentType VARCHAR(50),
        documentNo VARCHAR(50),
        customerNo VARCHAR(50),
        vendorNo VARCHAR(50),
        description VARCHAR(255),
        balAccountNo VARCHAR(50),
        amount DECIMAL(18,4),
        globalDimension1Code VARCHAR(50),
        globalDimension2Code VARCHAR(50),
        userID VARCHAR(50),
        sourceCode VARCHAR(50),
        priorYearEntry TINYINT(1),
        quantity DECIMAL(18,4),
        journalBatchName VARCHAR(50),
        genPostingType VARCHAR(50),
        genBusPostingGroup VARCHAR(50),
        debitAmount DECIMAL(18,4),
        creditAmount DECIMAL(18,4),
        documentDate DATE,
        externalDocumentNo VARCHAR(50),
        sourceType VARCHAR(50),
        sourceNo VARCHAR(50),
        reversedByEntryNo INT,
        reversedEntryNo INT,
        gLAccountName VARCHAR(150),
        shortcutDimension3Code VARCHAR(50),
        shortcutDimension4Code VARCHAR(50),
        lastModifiedDateTime DATETIME,
        wmsDocumentNo VARCHAR(50),
        wmsDocumentLineNo INT,
        noSeries VARCHAR(50),
        isCorrectieOfJaarafsluiting BIT NOT NULL,
        isUTB BIT NULL,
        commercialLocationNo VARCHAR(50),
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: wmsDocumentHeaders
      columns: "
        id CHAR(36) NOT NULL,
        documentType VARCHAR(50),
        no VARCHAR(50),
        sellToCustomerNo VARCHAR(50),
        buildingCode VARCHAR(50),
        postingDate DATE,
        statusCode VARCHAR(50),
        containerNo VARCHAR(50),
        vesselNo VARCHAR(50),
        senderAddressNo VARCHAR(50),
        shipToAddressNo VARCHAR(50),
        billOfLadingNo VARCHAR(50),
        shortcutDimension2Code VARCHAR(50),
        attribute04 VARCHAR(50),
        containerSizeCode VARCHAR(50),
        sellToCustomerName VARCHAR(150),
        billToCustomerNo VARCHAR(50),
        billToCustomerName VARCHAR(150),
        salespersonCode VARCHAR(50),
        direction VARCHAR(20),
        locationNo VARCHAR(50),
        movementType VARCHAR(50),
        documentDate DATE,
        orderDate DATE,
        statusTemplateCode VARCHAR(50),
        createdDateTime DATETIME,
        modifiedDateTime DATETIME,
        noSeries VARCHAR(50),
        externalDocumentNo VARCHAR(50),
        externalReference VARCHAR(50),
        shippingAgentCode VARCHAR(50),
        announcedDate DATE,
        arrivedDate DATE,
        departedDate DATE,
        deliveryDate DATE,
        estimatedDepartureDate DATE,
        parentDocumentType VARCHAR(50),
        parentDocumentNo VARCHAR(50),
        customsCode VARCHAR(50),
        tariffNo VARCHAR(50),
        countryOfOriginCode VARCHAR(50),
        countryOfDestinationCode VARCHAR(50),
        declarationDate DATE,
        destination VARCHAR(100),
        expectQtyCarriers INT,
        customsValue DECIMAL(18,2),
        incotermsCode VARCHAR(50),
        invoiceValue DECIMAL(18,2),
        incotermsCity VARCHAR(100),
        additionalDocumentNo VARCHAR(50),
        certificateNo VARCHAR(50),
        shortcutDimension1Code VARCHAR(50),
        attribute05 VARCHAR(50),
        grossWeight DECIMAL(18,2),
        netWeight DECIMAL(18,2),
        quantity DECIMAL(18,2),
        carrierQuantity DECIMAL(18,2),
        portFrom VARCHAR(50),
        portTo VARCHAR(50),
        sealNo VARCHAR(50),
        sendersAddressName VARCHAR(100),
        shipToAddressName VARCHAR(100),
        sendersAddressCity VARCHAR(100),
        shipToAddressCity VARCHAR(100),
        carrierQtyCreated INT,
        consigneeName VARCHAR(100),
        shipperName VARCHAR(100),
        agentName VARCHAR(100),
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: customerLedgerEntries
      columns: "
        id CHAR(36) NOT NULL,
        entryNo INT,
        customerNo VARCHAR(50),
        postingDate DATE,
        documentNo VARCHAR(50),
        description VARCHAR(255),
        originalAmtLCY DECIMAL(18,2),
        remainingAmtLCY DECIMAL(18,2),
        customerPostingGroup VARCHAR(50),
        open BOOLEAN,
        dueDate DATE,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: vendorLedgerEntries
      columns: "
        id CHAR(36) NOT NULL,
        entryNo INT,
        vendorNo VARCHAR(50),
        postingDate DATE,
        documentNo VARCHAR(50),
        description VARCHAR(255),
        originalAmtLCY DECIMAL(18,2),
        remainingAmtLCY DECIMAL(18,2),
        amountLCY DECIMAL(18,2),
        purchaseLCY DECIMAL(18,2),
        open BOOLEAN,
        dueDate DATE,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: wmsDocumentContainers
      columns: "
        id CHAR(36) NOT NULL,
        documentType VARCHAR(50),
        documentNo VARCHAR(50),
        lineNo INT,
        containerNo VARCHAR(50),
        sizeCode VARCHAR(20),
        loadingAddressNo VARCHAR(50),
        loadingReference VARCHAR(100),
        loadingAddressName VARCHAR(100),
        loadingAddressCity VARCHAR(100),
        unloadingAddressNo VARCHAR(50),
        unloadingReference VARCHAR(100),
        unloadingAddressName VARCHAR(100),
        unloadingAddressCity VARCHAR(100),
        pickUpAddressNo VARCHAR(50),
        pickUpReference VARCHAR(100),
        pickUpAddressName VARCHAR(100),
        pickUpAddressCity VARCHAR(100),
        dropOffAddressNo VARCHAR(50),
        dropOffReference VARCHAR(100),
        dropOffAddressName VARCHAR(100),
        dropOffAddressCity VARCHAR(100),
        loadingDateFrom DATE,
        loadingDateTo DATE,
        loadingTimeFrom TIME,
        loadingTimeTo TIME,
        unloadingDateFrom DATE,
        unloadingDateTo DATE,
        unloadingTimeFrom TIME,
        unloadingTimeTo TIME,
        inDemurrageDate DATE,
        inDetentionDate DATE,
        shippingCompanyAddress VARCHAR(255),
        shippingCompanyName VARCHAR(100),
        etdDate DATE,
        etdTime TIME,
        etaDate DATE,
        etaTime TIME,
        vesselNo VARCHAR(50),
        vesselname VARCHAR(100),
        billOfLadingNo VARCHAR(50),
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: wmsPostedDocumentHeaders
      columns: "
        id CHAR(36) NOT NULL,
        documentType VARCHAR(50),
        no VARCHAR(50),
        sellToCustomerNo VARCHAR(50),
        sellToCustomerName VARCHAR(100),
        billToCustomerName VARCHAR(100),
        buildingCode VARCHAR(50),
        salespersonCode VARCHAR(50),
        direction VARCHAR(20),
        documentDate DATE,
        postingDate DATE,
        statusCode VARCHAR(20),
        modifiedDateTime DATETIME,
        deliveryDate DATE,
        customsCode VARCHAR(50),
        sendersAddressName VARCHAR(100),
        shipToAddressName VARCHAR(100),
        shortcutDimension2Code VARCHAR(50),
        attribute04 VARCHAR(100),
        attribute05 VARCHAR(100),
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: wmsPostedDocumentLines
      columns: "
        id CHAR(36) NOT NULL,
        documentNo VARCHAR(50),
        lineNo INT,
        sellToCustomerNo VARCHAR(50),
        lineAmountLCY DECIMAL(18,2),
        no VARCHAR(50),
        description VARCHAR(255),
        quantity DECIMAL(18,2),
        modifiedDateTime DATETIME,
        grossWeight DECIMAL(18,2),
        netWeight DECIMAL(18,2),
        containerNo VARCHAR(50),
        vesselNo VARCHAR(50),
        postingDate DATE,
        isUTB BIT NULL,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: wmsDocumentPackageLines
      columns: "
        id CHAR(36) NOT NULL,
        documentType VARCHAR(50),
        documentNo VARCHAR(50),
        documentLineNo INT,
        packageCode VARCHAR(50),
        numberOfPackages INT,
        description VARCHAR(255),
        cubage DECIMAL(18,2),
        grossWeight DECIMAL(18,2),
        containerLineNo INT,
        containerNo VARCHAR(50),
        modifiedDateTime DATETIME,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: wmsDocumentCommentLines
      columns: "
        id CHAR(36) NOT NULL,
        documentType VARCHAR(50),
        documentNo VARCHAR(50),
        documentLineNo INT,
        lineNo INT,
        date DATE,
        code VARCHAR(50),
        comment VARCHAR(255),
        instruction VARCHAR(255),
        source VARCHAR(50),
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: purchaseHeaders
      columns: "
        id CHAR(36) NOT NULL,
        documentType VARCHAR(50),
        no VARCHAR(50),
        payToVendorNo VARCHAR(50),
        payToName VARCHAR(100),
        yourReference VARCHAR(100),
        orderDate DATE,
        postingDate DATE,
        purchaserCode VARCHAR(50),
        amount DECIMAL(18,2),
        amountIncludingVAT DECIMAL(18,2),
        vendorInvoiceNo VARCHAR(50),
        documentDate DATE,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

    - name: statusLog
      columns: "
        id CHAR(36) NOT NULL,
        systemModifiedAt DATETIME,
        entryNo BIGINT,
        documentNo VARCHAR(50),
        oldStatusCode VARCHAR(50),
        newStatusCode VARCHAR(50),
        userID VARCHAR(50),
        templateCode VARCHAR(50),
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
      indexes:
        - name: IX_Id
          columns:
            - id

  meta:
    # - name: internalEntities
    #   columns: "
    #     [entity_name] NVARCHAR(255) NOT NULL,
    #     [id] INT NOT NULL PRIMARY KEY,
    #     [entity_id] UNIQUEIDENTIFIER NOT NULL,
    #     [matching_name] NVARCHAR(255) NULL,
    #     insertedTimestamp DATETIMEOFFSET NOT NULL
    #     CONSTRAINT $NAME_ts DEFAULT SYSDATETIMEOFFSET()
    #     "
    - name: generalLedgerAccounts
      columns: "
        id CHAR(36) NOT NULL,
        no VARCHAR(30),
        no2 VARCHAR(30),
        name VARCHAR(100),
        incomeBalance VARCHAR(50),
        accountCategory VARCHAR(50),
        accountSubcategoryEntryNo INT,
        accountSubcategoryDescription VARCHAR(100),
        debitCredit VARCHAR(10),
        accountType VARCHAR(50),
        totaling VARCHAR(100),
        balance DECIMAL(18,2),
        lastModifiedDateTime DATETIME,
        genPostingType VARCHAR(50),
        vatProdPostingGroup VARCHAR(50),
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"

    - name: wmsAddresses
      columns: "
        id CHAR(36) NOT NULL,
        no VARCHAR(50),
        name VARCHAR(100),
        address VARCHAR(255),
        city VARCHAR(100),
        countryRegionName VARCHAR(100),
        modifiedDateTime DATETIME,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"

    - name: wmsBuildings
      columns: "
        id CHAR(36) NOT NULL,
        code VARCHAR(50),
        name VARCHAR(100),
        addressNo VARCHAR(50),
        conditionSetID INT,
        modifiedDateTime DATETIME,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"

    - name: customers
      columns: "
        id CHAR(36) NOT NULL,
        no VARCHAR(50),
        name VARCHAR(100),
        city VARCHAR(100),
        ourAccountNo VARCHAR(50),
        territoryCode VARCHAR(50),
        globalDimension1Code VARCHAR(50),
        globalDimension2Code VARCHAR(50),
        chainName VARCHAR(100),
        salespersonCode VARCHAR(50),
        countryRegionCode VARCHAR(50),
        comment BOOLEAN,
        blocked VARCHAR(50),
        paymentMethodCode VARCHAR(50),
        lastModifiedDateTime DATETIME,
        salesLCY DECIMAL(18,2),
        profitLCY DECIMAL(18,2),
        balanceDueLCY DECIMAL(18,2),
        paymentsLCY DECIMAL(18,2),
        invAmountsLCY DECIMAL(18,2),
        crMemoAmountsLCY DECIMAL(18,2),
        outstandingOrdersLCY DECIMAL(18,2),
        outstandingInvoicesLCY DECIMAL(18,2),
        noOfQuotes INT,
        noOfBlanketOrders INT,
        noOfOrders INT,
        noOfInvoices INT,
        noOfReturnOrders INT,
        noOfCreditMemos INT,
        lastInvoiced3PL DATE,
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"

    - name: contacts
      columns: "
        id CHAR(36) NOT NULL,
        systemModifiedAt DATETIME,
        no VARCHAR(50),
        type VARCHAR(50),
        name VARCHAR(100),
        searchName VARCHAR(100),
        city VARCHAR(100),
        eMail VARCHAR(150),
        companyNo VARCHAR(50),
        companyName VARCHAR(100),
        customerNo3PL VARCHAR(50),
        vendorNo3PL VARCHAR(50),
        statusCode3PL VARCHAR(50),
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"

    - name: vendors
      columns: "
        id CHAR(36) NOT NULL,
        no VARCHAR(50),
        name VARCHAR(150),
        city VARCHAR(100),
        ourAccountNo VARCHAR(50),
        territoryCode VARCHAR(50),
        globalDimension1Code VARCHAR(50),
        globalDimension2Code VARCHAR(50),
        budgetedAmount DECIMAL(18,2),
        shipmentMethodCode VARCHAR(50),
        priority INT,
        lastModifiedDateTime DATETIME,
        balanceLCY DECIMAL(18,2),
        invDiscountsLCY DECIMAL(18,2),
        pmtDiscountsLCY DECIMAL(18,2),
        balanceDueLCY DECIMAL(18,2),
        invAmountsLCY DECIMAL(18,2),
        outstandingOrders DECIMAL(18,2),
        reminderAmountsLCY DECIMAL(18,2),
        outstandingInvoicesLCY DECIMAL(18,2),
        noOfOrders INT,
        noOfInvoices INT,
        noOfReturnOrders INT,
        noOfCreditMemos INT,
        statusCode3PL VARCHAR(50),
        insertedTimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (id)"
